# STA130 TUT 02 (Sep13)<br><br> 👨‍💻 👩🏻‍💻 <u>Coding with data types, for loops, and logical control<u>



## ♻️ 📚 Review / Questions [10 minutes]
1. Follow up questions and clarifications regarding regarding **notebooks, markdown, ChatBots, or `Python` code** previously introduced in the Sep06 TUT and Sep09 LEC 

> 1. We're continuing to dive into using **notebooks, markdown**, and `Python` as a tool: building comfort and capability working with **ChatBots** to leverage `Python` code is the objective of the current phase of the course...<br><br>
>
> 2. *Questions about [HW01](https://github.com/pointOfive/stat130chat130/blob/main/HW/STA130F24_HW01_DueSep12.ipynb) which was due yesterday (Thursday Sep12) should be asked in OH from 4-6PM ET Tuesday, Wednesday, and Thursday (see the [Quercus course homepage](https://q.utoronto.ca/courses/354091) for further details)*<br><br>
> 
> 3. *And same story, and even moreso for questions about [HW02](https://github.com/pointOfive/stat130chat130/blob/main/HW/STA130F24_HW02_DueSep19.ipynb) which was due next Thursday (Sep19) (e.g., regarding the "pre-lecture" questions...)*

## 🚧 🏗️ Demo (using Jupyter Notebook and ChatBots) [50 minutes]


#### 1. **[35 of the 50 minutes]** Demonstrate (using a ChatBot to show and explain?) some traditional `python` coding structures

1. `tuple()`, `list()`, vs `dict()  # immutable and mutable "lists" vs key-value pairs`<br><br>
    
2. some `NumPy` functions:<br><br>
    
    1. `import numpy as np`
    2. `np.array([1,2,3]) # a faster "list"`
    3. `np.random.choice([1,2,3])`<br><br>
        
3. `for i in range(n):`, `for x in a_list:`, `for i,x in enumerate(a_list):`, and `print()`<br><br>
    
    1. `variable` as the last line of a "code cell" in a notebook "prints" the value
    2. but `print()` is needed inside `for` loop if you want to output something<br><br>
        
4. `if`/`else` conditional statements<br><br> 

    1. perhaps with `x in b_list`<br>or `i % 2 == 0` to treat evens/odds differently  (sort of like the infamous "FizzBuzz" problem that some people [can't complete](https://www.quora.com/On-average-what-is-the-proportion-of-applicants-that-cannot-pass-a-simple-FizzBuzz-test-based-on-your-personal-experience-or-on-facts) as part of a coding interview challenge)
    2. note the "similarity" to the `try-except` block structure when that's encountered in the code below since it's used there (despite being a "more advanced" 
        
#### 2. **[5 of the 50 minutes]** Reintroduce the [Monty Hall problem](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/GPT/SLS/00001_gpt3p5_MonteHall_ProblemExplanation_v1.md) and see which of the coding structures above you recognize (or do not see) in the Monty Hall simulation code below

#### 3. **[10 of the 50 minutes]** Use any remaining time to start a demonstration of using a ChatBot to (a) understand what the code below is doing and (b) suggest an improved streamlined version of the `for` loop simulation code that might be easier to explain and understand
    
> ChatGPT version 3.5 [was very effective](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/GPT/SLS/00003_gpt3p5_MonteHall_CodeDiscussion_v1.md) for (b), while Copilot was shockingly bad on a [first try](../CHATLOG/wk2/COP/SLS/00001_creative_MonteHall_CodeDiscussion_v1.md) but was able to do better [with some helpful guidance](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/COP/SLS/00002_concise_MonteHall_CodeDiscussion_v2.md).

## 1. Demonstrate some traditional python coding structures

**1.1. Data types: Tuples, Lists, and Dictionaries**
- Tuples: `tuple()`

    - Definition: An ordered, **immutable** collection of elements.
    - Syntax: my_tuple = (1, 2, 3)
    - Usage: Useful when you need a fixed set of values that shouldn't change.
    - Key Point: Tuples cannot be modified (no adding/removing elements).

- Lists: `list()`

    - Definition: An ordered, **mutable** collection of elements.
    - Syntax: my_list = [1, 2, 3]
    - Usage: Use lists when you need a flexible sequence of items.
    - Key Point: Lists can be changed (add/remove elements).

- Dictionaries: `dict()`

    - Definition: A collection of **key-value pairs**.
    - Syntax: my_dict = {'key1': 'value1', 'key2': 'value2'}
    - Usage: Use dictionaries to store data that needs to be labeled.
    - Key Point: Keys must be unique and immutable, values can be changed.

In [3]:
# Q: Demonstrate how a tuple works in Python
# Creating a tuple with different data types
my_tuple = (1, "apple", 3.14, True)
print(my_tuple)  # Output: (1, 'apple', 3.14, True)

# Accessing elements
print(my_tuple[0])  # Output: 1
print(my_tuple[1])  # Output: 'apple'

# Negative indexing
print(my_tuple[-1])  # Output: True

# Slicing a tuple
print(my_tuple[1:3])  # Output: ('apple', 3.14)

# Trying to change an element (will raise an error)
# my_tuple[0] = 10  # Uncommenting this line will raise a TypeError

# Packing
packed_tuple = (10, 20, 30)

# Unpacking
a, b, c = packed_tuple
print(a)  # Output: 10
print(b)  # Output: 20
print(c)  # Output: 30

# Counting the occurrences of a value
print(my_tuple.count(1))  # Output: 2 (counts True as 1)

# Finding the index of an element
print(my_tuple.index("apple"))  # Output: 1

# Nested tuples
nested_tuple = (1, (2, 3), (4, 5, 6))
print(nested_tuple[1])  # Output: (2, 3)

(1, 'apple', 3.14, True)
1
apple
True
('apple', 3.14)
10
20
30
2
1
(2, 3)


In [4]:
# Q: Demonstrate how a list works in Python.
# 1. Creating a List
# A list can contain integers, strings, floats, and even other lists.
my_list = [10, "apple", 3.14, True]
print(my_list)  # Output: [10, 'apple', 3.14, True]

# 2. Accessing Elements
# Lists are indexed starting at 0. You can access elements using their index.
print(my_list[0])  # Output: 10
print(my_list[1])  # Output: 'apple'

# Negative indexing allows you to access elements from the end of the list.
print(my_list[-1])  # Output: True

# 3. Modifying Elements
# Since lists are mutable, you can change their elements.
my_list[0] = 20
print(my_list)  # Output: [20, 'apple', 3.14, True]

# 4. Adding Elements
# You can add elements using append(), insert(), or extend().
my_list.append("banana")  # Adds 'banana' at the end
print(my_list)  # Output: [20, 'apple', 3.14, True, 'banana']

# Using insert() to add an element at a specific position
my_list.insert(1, "orange")  # Adds 'orange' at index 1
print(my_list)  # Output: [20, 'orange', 'apple', 3.14, True, 'banana']

# Using extend() to add multiple elements
my_list.extend([1, 2, 3])  # Adds [1, 2, 3] to the end of the list
print(my_list)  # Output: [20, 'orange', 'apple', 3.14, True, 'banana', 1, 2, 3]

# 5. Removing Elements
# You can remove elements using remove(), pop(), or del.
my_list.remove("apple")  # Removes the first occurrence of 'apple'
print(my_list)  # Output: [20, 'orange', 3.14, True, 'banana', 1, 2, 3]

# Using pop() to remove an element by index and return it
popped_item = my_list.pop(0)  # Removes and returns the first element
print(popped_item)  # Output: 20
print(my_list)  # Output: ['orange', 3.14, True, 'banana', 1, 2, 3]

# Using del to remove an element by index
del my_list[1]  # Deletes the element at index 1
print(my_list)  # Output: ['orange', True, 'banana', 1, 2, 3]

# 6. Slicing Lists
# You can slice lists to create sublists.
sliced_list = my_list[1:4]  # Slices from index 1 to 3 (excludes index 4)
print(sliced_list)  # Output: [True, 'banana', 1]

# 7. Iterating Over a List
# You can loop through a list using a for loop.
for item in my_list:
    print(item)

# 8. List Methods
# Lists have many built-in methods like sort(), reverse(), count(), and index().
my_list = [3, 1, 4, 1, 5, 9]
my_list.sort()  # Sorts the list in ascending order
print(my_list)  # Output: [1, 1, 3, 4, 5, 9]

my_list.reverse()  # Reverses the order of the list
print(my_list)  # Output: [9, 5, 4, 3, 1, 1]

# Counting occurrences of an element
print(my_list.count(1))  # Output: 2

# Finding the index of an element
print(my_list.index(4))  # Output: 2

# 9. Nested Lists
# Lists can contain other lists, allowing for multidimensional data structures.
nested_list = [[1, 2, 3], ["a", "b", "c"]]
print(nested_list[0])  # Output: [1, 2, 3]
print(nested_list[1][1])  # Output: 'b'

# 10. List Comprehensions
# List comprehensions provide a concise way to create lists.
squares = [x ** 2 for x in range(5)]
print(squares)  # Output: [0, 1, 4, 9, 16]

[10, 'apple', 3.14, True]
10
apple
True
[20, 'apple', 3.14, True]
[20, 'apple', 3.14, True, 'banana']
[20, 'orange', 'apple', 3.14, True, 'banana']
[20, 'orange', 'apple', 3.14, True, 'banana', 1, 2, 3]
[20, 'orange', 3.14, True, 'banana', 1, 2, 3]
20
['orange', 3.14, True, 'banana', 1, 2, 3]
['orange', True, 'banana', 1, 2, 3]
[True, 'banana', 1]
orange
True
banana
1
2
3
[1, 1, 3, 4, 5, 9]
[9, 5, 4, 3, 1, 1]
2
2
[1, 2, 3]
b
[0, 1, 4, 9, 16]


In [5]:
# Q: Demonstrate how dict() works in Python.
# 1. Creating a Dictionary
# You can create a dictionary using curly braces {} or the dict() function.

# Using curly braces
my_dict = {"name": "Alice", "age": 25, "city": "Toronto"}
print(my_dict)  # Output: {'name': 'Alice', 'age': 25, 'city': 'Toronto'}

# Using the dict() function
another_dict = dict(name="Bob", age=30, city="Vancouver")
print(another_dict)  # Output: {'name': 'Bob', 'age': 30, 'city': 'Vancouver'}

# 2. Accessing Values
# Access values by referring to their key inside square brackets or using the get() method.
print(my_dict["name"])  # Output: Alice
print(my_dict.get("age"))  # Output: 25

# Using get() with a default value to avoid KeyError if the key doesn't exist
print(my_dict.get("country", "Canada"))  # Output: Canada

# 3. Adding and Modifying Elements
# Add new key-value pairs or modify existing ones by assigning a value to a key.
my_dict["profession"] = "Engineer"  # Adding a new key-value pair
print(my_dict)  # Output: {'name': 'Alice', 'age': 25, 'city': 'Toronto', 'profession': 'Engineer'}

my_dict["age"] = 26  # Modifying an existing key
print(my_dict)  # Output: {'name': 'Alice', 'age': 26, 'city': 'Toronto', 'profession': 'Engineer'}

# 4. Removing Elements
# Use pop(), del, or popitem() to remove elements.

# Using pop() to remove a key and return its value
removed_value = my_dict.pop("city")
print(removed_value)  # Output: Toronto
print(my_dict)  # Output: {'name': 'Alice', 'age': 26, 'profession': 'Engineer'}

# Using del to remove a key
del my_dict["profession"]
print(my_dict)  # Output: {'name': 'Alice', 'age': 26}

# Using popitem() to remove and return the last inserted key-value pair
my_dict["country"] = "Canada"
last_item = my_dict.popitem()
print(last_item)  # Output: ('country', 'Canada')
print(my_dict)  # Output: {'name': 'Alice', 'age': 26}

# 5. Checking Key Existence
# Use the `in` keyword to check if a key is in the dictionary.
print("name" in my_dict)  # Output: True
print("city" in my_dict)  # Output: False

# 6. Iterating Over a Dictionary
# You can loop through keys, values, or both using keys(), values(), and items().

# Iterating over keys
for key in my_dict:
    print(key)  # Output: name, age

# Iterating over values
for value in my_dict.values():
    print(value)  # Output: Alice, 26

# Iterating over key-value pairs
for key, value in my_dict.items():
    print(f"{key}: {value}")  # Output: name: Alice, age: 26

# 7. Merging Dictionaries
# Use the update() method to merge another dictionary into an existing one.
my_dict.update({"city": "Toronto", "country": "Canada"})
print(my_dict)  # Output: {'name': 'Alice', 'age': 26, 'city': 'Toronto', 'country': 'Canada'}

# 8. Dictionary Comprehension
# You can create dictionaries using comprehensions for concise and readable code.
squares = {x: x**2 for x in range(5)}
print(squares)  # Output: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

# 9. Nested Dictionaries
# Dictionaries can contain other dictionaries, allowing for complex data structures.
nested_dict = {
    "person1": {"name": "Alice", "age": 25},
    "person2": {"name": "Bob", "age": 30},
}
print(nested_dict["person1"]["name"])  # Output: Alice

# 10. Clearing and Copying a Dictionary
# Use clear() to empty a dictionary and copy() to create a shallow copy.
my_dict.clear()  # Clears all items from the dictionary
print(my_dict)  # Output: {}

# Copying a dictionary
original_dict = {"a": 1, "b": 2}
copied_dict = original_dict.copy()
print(copied_dict)  # Output: {'a': 1, 'b': 2}

{'name': 'Alice', 'age': 25, 'city': 'Toronto'}
{'name': 'Bob', 'age': 30, 'city': 'Vancouver'}
Alice
25
Canada
{'name': 'Alice', 'age': 25, 'city': 'Toronto', 'profession': 'Engineer'}
{'name': 'Alice', 'age': 26, 'city': 'Toronto', 'profession': 'Engineer'}
Toronto
{'name': 'Alice', 'age': 26, 'profession': 'Engineer'}
{'name': 'Alice', 'age': 26}
('country', 'Canada')
{'name': 'Alice', 'age': 26}
True
False
name
age
Alice
26
name: Alice
age: 26
{'name': 'Alice', 'age': 26, 'city': 'Toronto', 'country': 'Canada'}
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}
Alice
{}
{'a': 1, 'b': 2}


**1.2. Libraries: NumPy**

- What is NumPy: A powerful library for numerical computations, enabling fast array operations.
- Using this library by `import numpy as np`
- Basic Functions:
    - Creating Arrays: `np.array()`  (Notes: Arrays are faster and more efficient than Python lists for numerical data.)
    - Random Choice: `np.random.choice()`

In [ ]:
# Q: Explain how this code works: import numpy as np / what is numpy

In [6]:
# Q: Demonstrate how numpy.array works in Python.
# Importing the numpy library
import numpy as np

# 1. Creating Arrays with numpy.array
# Creating a 1D array (vector)
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)  # Output: [1 2 3 4 5]

# Creating a 2D array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", array_3d)
# Output:
# [[[1 2]
#   [3 4]]
#
#  [[5 6]
#   [7 8]]]

# 2. Specifying the Data Type
# By default, NumPy determines the data type, but you can specify it using the dtype parameter.
float_array = np.array([1, 2, 3], dtype=float)
print("\nFloat Array:", float_array)  # Output: [1. 2. 3.]

# 3. Accessing Elements
# Access elements using indices, similar to lists.
print("\nAccessing 2D Array Element (0, 1):", array_2d[0, 1])  # Output: 2

# 4. Array Operations
# Arrays allow element-wise operations without loops.
added_array = array_1d + 10
print("\nAdded 10 to each element:", added_array)  # Output: [11 12 13 14 15]

# Multiplying each element by 2
multiplied_array = array_2d * 2
print("\nMultiplied each element by 2:\n", multiplied_array)
# Output:
# [[ 2  4  6]
#  [ 8 10 12]]

# 5. Slicing Arrays
# You can slice arrays to access subsets of data.
print("\nSlicing the first row of the 2D array:", array_2d[0, :])  # Output: [1 2 3]

# Accessing a column
print("Slicing the second column:", array_2d[:, 1])  # Output: [2 5]

# 6. Reshaping Arrays
# Change the shape of an array using the reshape() method.
reshaped = np.reshape(array_1d, (5, 1))
print("\nReshaped 1D Array to 5x1:\n", reshaped)
# Output:
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]]

# 7. Array Attributes
# Exploring useful attributes of numpy arrays
print("\nArray Shape:", array_2d.shape)  # Output: (2, 3) -> 2 rows, 3 columns
print("Array Size:", array_2d.size)    # Output: 6 -> Total number of elements
print("Array Data Type:", array_2d.dtype)  # Output: int64 (or int32 depending on your system)
print("Number of Dimensions:", array_3d.ndim)  # Output: 3

# 8. Creating Arrays with Ranges
# Creating arrays with evenly spaced values using arange() and linspace()
range_array = np.arange(0, 10, 2)  # Start at 0, end before 10, step of 2
print("\nArray Created with arange:", range_array)  # Output: [0 2 4 6 8]

linspace_array = np.linspace(0, 1, 5)  # 5 values between 0 and 1, inclusive
print("Array Created with linspace:", linspace_array)  # Output: [0.   0.25 0.5  0.75 1.  ]

# 9. Mathematical Operations
# Applying mathematical operations to arrays
squared_array = np.square(array_1d)
print("\nSquared Elements:", squared_array)  # Output: [ 1  4  9 16 25]

# 10. Broadcasting
# Demonstrates how NumPy handles operations between arrays of different shapes
array_broadcast = array_1d + np.array([10])
print("\nBroadcasting Array Addition:", array_broadcast)  # Output: [11 12 13 14 15]

# 11. Array Copy vs. View
# Copy creates a new array, while a view is just a reference to the original data.
copy_array = array_1d.copy()
view_array = array_1d.view()
array_1d[0] = 100
print("\nOriginal Array Modified:", array_1d)  # Output: [100   2   3   4   5]
print("Copied Array Remains Unchanged:", copy_array)  # Output: [1 2 3 4 5]
print("View Reflects Changes:", view_array)  # Output: [100   2   3   4   5]

1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Float Array: [1. 2. 3.]

Accessing 2D Array Element (0, 1): 2

Added 10 to each element: [11 12 13 14 15]

Multiplied each element by 2:
 [[ 2  4  6]
 [ 8 10 12]]

Slicing the first row of the 2D array: [1 2 3]
Slicing the second column: [2 5]

Reshaped 1D Array to 5x1:
 [[1]
 [2]
 [3]
 [4]
 [5]]

Array Shape: (2, 3)
Array Size: 6
Array Data Type: int64
Number of Dimensions: 3

Array Created with arange: [0 2 4 6 8]
Array Created with linspace: [0.   0.25 0.5  0.75 1.  ]

Squared Elements: [ 1  4  9 16 25]

Broadcasting Array Addition: [11 12 13 14 15]

Original Array Modified: [100   2   3   4   5]
Copied Array Remains Unchanged: [1 2 3 4 5]
View Reflects Changes: [100   2   3   4   5]


In [7]:
# Q: Demonstrate how np.random.choice works in Python.
import numpy as np

# 1. Basic Usage: Selecting a Random Element from a List
# Selecting one random element from a list
random_element = np.random.choice([10, 20, 30, 40, 50])
print("Randomly Selected Element:", random_element)
# Output: A random element from the list, e.g., 30

# 2. Selecting Multiple Elements with Replacement
# Selecting 5 random elements with replacement (elements can be repeated)
multiple_elements = np.random.choice([1, 2, 3, 4, 5], size=5, replace=True)
print("\nMultiple Elements with Replacement:", multiple_elements)
# Output: An array of 5 elements, e.g., [3 1 4 4 2]

# 3. Selecting Multiple Elements without Replacement
# Selecting 3 unique elements (no replacement)
unique_elements = np.random.choice([1, 2, 3, 4, 5], size=3, replace=False)
print("\nMultiple Elements without Replacement:", unique_elements)
# Output: A unique set of 3 elements, e.g., [1 5 3]

# 4. Probability-Weighted Selection
# Assigning different probabilities to each element
weighted_choice = np.random.choice(['A', 'B', 'C'], size=10, p=[0.1, 0.3, 0.6])
print("\nWeighted Selection:", weighted_choice)
# Output: Random elements with probabilities A (10%), B (30%), and C (60%)
# e.g., ['C' 'C' 'B' 'C' 'B' 'C' 'C' 'C' 'B' 'C']

# 5. Using an Integer for `a`: Equivalent to np.arange(5)
# Randomly selecting elements from the range [0, 1, 2, 3, 4]
range_choice = np.random.choice(5, size=4)
print("\nSelecting from Range [0-4]:", range_choice)
# Output: A random selection from 0 to 4, e.g., [2 0 1 3]

# 6. Using Replace=False with Size Larger than Available Elements
# Attempting this will result in an error because it’s not possible
# to draw more unique elements than available without replacement
try:
    error_example = np.random.choice([1, 2, 3], size=5, replace=False)
except ValueError as e:
    print("\nError when trying to draw too many elements without replacement:", e)
# Output: ValueError: Cannot take a larger sample than population when 'replace=False'

# 7. Randomly Selecting Characters from a String
# Selecting random characters from a string
char_selection = np.random.choice(list("abcdef"), size=3)
print("\nRandom Character Selection:", char_selection)
# Output: A random selection of 3 characters, e.g., ['c' 'a' 'f']

Randomly Selected Element: 50

Multiple Elements with Replacement: [4 5 2 4 3]

Multiple Elements without Replacement: [5 1 4]

Weighted Selection: ['C' 'A' 'B' 'A' 'C' 'C' 'C' 'B' 'B' 'B']

Selecting from Range [0-4]: [4 4 2 1]

Error when trying to draw too many elements without replacement: Cannot take a larger sample than population when 'replace=False'

Random Character Selection: ['a' 'f' 'b']


**1.3. Loop Structures: For Loop**
- Basic Loop: `for i in range(n):`
- Looping Over Lists: `for x in a_list:`
- Enumerating Lists: `for i, x in enumerate(a_list):`

In [ ]:
# Q: What is a for loop

In [ ]:
# Q: Demonstrate the differences between for i in range(n), for x in a_list, and for i, x in enumerate(a_list)

**Print: `print()`**

In [3]:
# Q: What is print()? Demonstrate how it works

In [8]:
# Variables at the end of a code cell in a notebook will automatically "prints" the value.
a = 'hello world'
a

'hello world'

In [10]:
# Q: why print() is needed inside for loop if you want to output something?

for i in range(5):
    i

print(i)

4


**1.4. Conditional Statements: `if`/`else` Statement**
- Basic If-Else
- Using in

In [11]:
# Q: Use if/else statements in Python to create a program that outputs whether a number is odd or even.
# Function to check if a number is odd or even
def check_odd_even(number):
    if number % 2 == 0:
        print(f"{number} is even.")
    else:
        print(f"{number} is odd.")

# Example usage
number = int(input("Enter a number: "))
check_odd_even(number)


Enter a number: 7
7 is odd.


In [13]:
# Q: Demonstrate how if/else conditional statements work with x is in b_list
# Define a list
b_list = [10, 20, 30, 40, 50]

# Define a variable to check
x = int(input("Enter a number to check: "))

# Use if/else to check if x is in b_list
if x in b_list:
    print(f"{x} is in the list.")
else:
    print(f"{x} is not in the list.")


Enter a number to check: 20
20 is in the list.


In [14]:
# Q: Write Python code that solves the FizzBuzz test.
def fizz_buzz(n):
    for i in range(1, n + 1):
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)

# Example usage
n = int(input("Enter the number up to which FizzBuzz should be printed: "))
fizz_buzz(n)


Enter the number up to which FizzBuzz should be printed: 20
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


**Compare with Try-Except Blocks**

In [15]:
# Q: What is Try-Except Blocks?
try:
    numerator = int(input("Enter numerator: "))
    denominator = int(input("Enter denominator: "))
    result = numerator / denominator
    print(f"Result: {result}")

except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

except ValueError:
    print("Error: Invalid input. Please enter a valid number.")

finally:
    print("Execution complete.")

Enter numerator: 3
Enter denominator: 0
Error: Cannot divide by zero.
Execution complete.


In [4]:
# Q: Explain the similarities and differences between if/else conditional statements and try-except blocks in Python?

## 2. [Monty Hall problem](https://github.com/pointOfive/stat130chat130/blob/main/CHATLOG/wk2/GPT/SLS/00001_gpt3p5_MonteHall_ProblemExplanation_v1.md)
- A game show scenario where you choose between three doors; one hides a prize, and the host reveals a non-prize door after your initial choice. You can then choose to switch or stay.

### Q: Which of the coding structures above you recognize (or do not see) in the Monty Hall simulation code below?

In [1]:
# Monte Hall Simulation Code -- not the only way to code this, but it's what Prof. Schwartz came up with...
# Q: Explain what this Python code is doing.
import numpy as np
all_door_options = (1,2,3)  # tuple
my_door_choice = 1  # 1,2,3
i_won = 0
reps = 100000
for i in range(reps):
    secret_winning_door = np.random.choice(all_door_options)
    all_door_options_list = list(all_door_options)
    # take the secret_winning_door, so we don't show it as a "goat" losing door
    all_door_options_list.remove(secret_winning_door)
    try:
        # if my_door_choice was secret_winning_door then it's already removed
        all_door_options_list.remove(my_door_choice)
    except:
        pass
    # show a "goat" losing door and remove it
    goat_door_reveal = np.random.choice(all_door_options_list)
    all_door_options_list.remove(goat_door_reveal)

    # put the secret_winning_door back in if it wasn't our choice
    # we previously removed it, so it would be shown as a  "goat" losing door
    if secret_winning_door != my_door_choice:
        all_door_options_list.append(secret_winning_door)
    # if secret_winning_door was our choice then all that's left in the list is a "goat" losing door
    # if secret_winning_door wasn't our choice then it's all that will be left in the list

    # swap strategy
    my_door_choice = all_door_options_list[0]

    if my_door_choice == secret_winning_door:
        i_won += 1

i_won/reps

0.66777

In [20]:
# Q: Can you refine the code to be shorter or more efficient?
import numpy as np

all_door_options = [1, 2, 3]  # list (no need for tuple conversion later)
my_door_choice = 1  # 1, 2, or 3
i_won = 0
reps = 100000

for i in range(reps):
    secret_winning_door = np.random.choice(all_door_options)

    # Monty opens a goat door that is neither the chosen door nor the winning door
    remaining_doors = [door for door in all_door_options if door != my_door_choice and door != secret_winning_door]
    goat_door_reveal = np.random.choice(remaining_doors)

    # The player switches to the remaining door (the one not chosen or revealed)
    my_door_choice = [door for door in all_door_options if door != my_door_choice and door != goat_door_reveal][0]

    # Check if the new choice is the winning door
    if my_door_choice == secret_winning_door:
        i_won += 1

# Output the probability of winning by switching
print(i_won / reps)

0.66664


In [ ]:
# Q: Can you explain more clearly what the remaining_doors line is doing?

### Why do we need to use a loop? What is the idea behind using 100000 iterations?
> <details class="details-example"><summary style="color:blue"><u>Hints</u></summary>
>     
> A core statistical concept: repeated sampling!
>
> </details>

## 💬 🗣️ Communication [40 minutes]
    
#### 1. **[5 of the 40 minutes]** Quickly execute the "rule of 5" and take 5 minutes to break into 5 new groups of about 5 students and assign the following 5 questions to the 5 groups (and note that this instruction uses fives 5's 😉). Consider allowing students to preferentially select which group they join by calling for volunteers for each prompt, and feel free to use 5 minutes from the next (dicussion) sections doing so if you choose to (since this could be viewed as being a part of the "discussion").

> *For each of the prompts, groups should consider the pros and cons of two options, the potential impact of a decision to persue one of the options, and how they take into account how uncertainty influences their thinking about the options.<br><br>*
>
> <details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>
>     
> I asked a ChatBot to create a group activity for you that was related to decision-making under uncertainty using probability, and it produced the following questions. 
> 
> *This is a little bit like one of the ideas in the "Afterward" of HW01 asking a ChatBot to suggest and explain some other, perhaps less well-known "unintuitive surprising statistics paradoxes" (besides the "World War 2 Plane" and "Monte Hall" problems)*
>
> </details>

1. **Stock Investment Strategy:** Students are investors trying to maximize their returns in the stock market. They must decide between two investment strategies: "diversified portfolio" or "focused portfolio." Each strategy has different probabilities of success based on market conditions.<br><br>
    
    1. Diversified Portfolio: Spread investments across multiple industries.
    2. Focused Portfolio: Concentrate investments in a few high-potential stocks.<br><br>
        
2. **Healthcare Treatment Decision:** Students are healthcare professionals deciding between two treatment options for a patient's condition. Each treatment has different success rates and potential side effects.<br><br>
    
    1. Treatment A: High success rate but moderate side effects.
    2. Treatment B: Lower success rate but minimal side effects.<br><br>
        
3. **Sports Team Strategy:** Students are coaches of a sports team planning their game strategy. They must decide between two tactics: "offensive strategy" or "defensive strategy." Each strategy has different probabilities of winning based on the opponent's strengths and weaknesses.<br><br>
    
    1. Offensive Strategy: Focus on scoring goals/points aggressively.
    2. Defensive Strategy: Prioritize defense to prevent the opponent from scoring.<br><br>
        
4. **Career Path Decision:** Students are recent graduates deciding between two career paths: "corporate job" or "entrepreneurship." Each path has different probabilities of success and factors to consider, such as job security, income potential, and work-life balance.<br><br>
    
    1. Corporate Job: Stable income but limited growth opportunities.
    2. Entrepreneurship: Higher potential for success but greater risk and uncertainty.<br><br>
        
5. **Environmental Conservation Strategy:** Students are environmental activists advocating for conservation efforts in a wildlife reserve. They must decide between two conservation strategies: "habitat preservation" or "species reintroduction." Each strategy has different probabilities of achieving long-term sustainability for the ecosystem.<br><br>
    
    1. Habitat Preservation: Protect existing habitats from human encroachment.
    2. Species Reintroduction: Reintroduce endangered species to restore ecological balance.


#### 2. **[15 to 20 of the 40 minutes]** Each group plans and prepares a brief (approximately 3 minute) summary (a) introducing their problem context and (b) outlining their decision and the rationale behind it. The group presentations should address

1. the expected outcomes of their decision
2. the risks involved
3. and why they believe their choice is the best in light of their characterization of the degree uncertainty present in their context 

#### 3. **[15 to 20 of the 40 minutes]** Each group gives their (approximately 3 minute) planned presentation. If time permits, engaging in some (students or TA) Q&A seeking clarification or challenging group decisions would be ideal.

Groups who manage to plan a presentation where multiple group members actively part of the presentation should be awarded "gold stars", figuratively, of course, since actualy gold, or stars, of gold star stickers are unfortunately momentarily in short supply

## Summary

**https://chatgpt.com/share/66e457ba-eacc-8007-b9d9-a6201756b42d**

1. **Code Explanation**: You provided Python code simulating the Monty Hall problem, and I explained its functionality, focusing on how it manages door choices and switches strategies.
   
2. **Code Refinement**: You asked for a more efficient version of the code, which I provided, but an `IndexError` occurred due to issues with managing the `remaining_doors` list.

3. **Error Troubleshooting**: I identified that the `IndexError` happened because `remaining_doors` was empty when trying to access its element. I explained the adjustments made to ensure the list operations were safe and robust.

4. **Detailed Explanation of `remaining_doors`**: I explained how the `remaining_doors` line works, detailing the list comprehension used to exclude the secret winning door and why this step is critical in managing the door-switching process in the Monty Hall simulation.

5. **Conceptual Understanding**: The explanation provided insights into why `remaining_doors` is used to identify which doors are left after revealing a goat door, emphasizing its role in the simulation’s switching strategy.